FROM postgres:11.3

# RUN echo "host all  all    0.0.0.0/0  md5" >> $PG_CONFIG_DIR/pg_hba.conf \
#       && echo "host all  all    ::/0  md5" >> $PG_CONFIG_DIR/pg_hba.conf \
#       && echo "listen_addresses='*'" >> $PG_CONFIG_FILE

CMD ["sleep", "infinity"]